### ISSUE TITLE
screenprint not installing

### ISSUE THREAD

**Issue by catchwayrk** [cyrildiagne/ar-cutpaste#16]
i am getting below issue(venv) RKMadugulas-MacBook-Pro:server yesbro$ sudo pip install -r requirements.txt
Password:
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
WARNING: The directory '/Users/yesbro/Library/Caches/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: photoshop-connection==0.1.1 in ./venv/lib/python2.7/site-packages (from -r requirements.txt (line 1)) (0.1.1)
Requirement already satisfied: Flask==1.1.1 in ./venv/lib/python2.7/site-packages (from -r requirements.txt (line 2)) (1.1.1)
Requirement already satisfied: flask-cors==3.0.8 in ./venv/lib/python2.7/site-packages (from -r requirements.txt (line 3)) (3.0.8)
Requirement already satisfied: pyscreenshot==1.0 in ./venv/lib/python2.7/site-packages (from -r requirements.txt (line 4)) (1.0)
Requirement already satisfied: requests==2.23.0 in ./venv/lib/python2.7/site-packages (from -r requirements.txt (line 5)) (2.23.0)
Collecting screenpoint==0.1.1
  Downloading screenpoint-0.1.1.tar.gz (2.8 kB)
    ERROR: Command errored out with exit status 1:
     command: '/Volumes/Projects/ionic/Loophole/AR cut Paste/ar-cutpaste-master/server/venv/bin/python' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/tmp/pip-install-ggyDYe/screenpoint/setup.py'"'"'; __file__='"'"'/private/tmp/pip-install-ggyDYe/screenpoint/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/tmp/pip-pip-egg-info-SUX4tg
         cwd: /private/tmp/pip-install-ggyDYe/screenpoint/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-install-ggyDYe/screenpoint/setup.py", line 6, in <module>
        with open(path.join(this_directory, 'README.md'), encoding='utf-8') as f:
    TypeError: 'encoding' is an invalid keyword argument for this function
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
 while running the requirements.txt file

**Comment by cyrildiagne** [comment]
Hi,

Looks like you're using python 2.7 but this library is only compatible with Python 3.
Could you try again on Python 3?

**Comment by catchwayrk** [comment]
(venv) RKMadugulas-MacBook-Pro:server yesbro$ python --version
Python 2.7.10
(venv) RKMadugulas-MacBook-Pro:server yesbro$ python3 --version
Python 3.8.2


i am bit confused with python version can you please explain me how to update the latest version of python

**Comment by immortal3** [comment]
@catchwayrk try installing libs with 
```
sudo pip3 install -r requirements.txt
```

and then run code with
```
python3 main.py
```

**Comment by buskerone** [comment]
@immortal3 is right! I was facing the same issue and using python3 solved everything.

**Comment by catchwayrk** [comment]
yes almost working fine , but now I got new issue 

ERROR: Could not find a version that satisfies the requirement opencv-contrib-python==3.4.2.17 (from screenpoint==0.1.1) (from versions: 3.4.8.29, 3.4.9.31, 3.4.9.33, 4.1.2.30, 4.2.0.32, 4.2.0.34)
ERROR: No matching distribution found for opencv-contrib-python==3.4.2.17 (from screenpoint==0.1.1)
can you please help

**Comment by catchwayrk** [comment]
RKMadugulas-MacBook-Pro:src yesbro$ python3 main.py
Traceback (most recent call last):
  File "main.py", line 8, in <module>
    import screenpoint
ModuleNotFoundError: No module named 'screenpoint'
RKMadugulas-MacBook-Pro:src yesbro$

**Comment by catchwayrk** [comment]
(venv) RKMadugulas-MacBook-Pro:Downloads yesbro$ pip3 list
Package                        Version
------------------------------ ----------
certifi                        2020.4.5.1
chardet                        3.0.4
click                          7.1.2
EasyProcess                    0.3
entrypoint2                    0.2.1
Flask                          1.1.2
Flask-Cors                     3.0.8
idna                           2.9
itsdangerous                   1.1.0
Jinja2                         2.11.2
MarkupSafe                     1.1.1
numpy                          1.18.4
opencv-contrib-python          4.2.0.34
opencv-contrib-python-headless 4.2.0.34
opencv-python                  4.2.0.34
opencv-python-headless         4.2.0.34
Pillow                         7.1.2
pip                            20.1
pyscreenshot                   1.0
requests                       2.23.0
setuptools                     46.1.3
six                            1.14.0
urllib3                        1.25.9
Werkzeug                       1.0.1
wheel                          0.34.2
(venv) RKMadugulas-MacBook-Pro:Downloads yesbro$ 



except screen point rest all installed

**Comment by cyrildiagne** [comment]
Looks like this version of openCV is no longer available in Python 3.8: https://github.com/cyrildiagne/screenpoint/issues/1

Could you try using Python 3.7?

The issue has been reported in the screenpoint repo. I'll update the dependency version here when fixed.

**Comment by catchwayrk** [comment]
> Looks like this version of openCV is no longer available in Python 3.8: [cyrildiagne/screenpoint#1](https://github.com/cyrildiagne/screenpoint/issues/1)
> 
> Could you try using Python 3.7?
> 
> The issue has been reported in the screenpoint repo. I'll update the dependency version here when fixed.

this worked python 3.8 not working.

**Comment by catchwayrk** [comment]
(venv) RKMadugulas-MacBook-Pro:server yesbro$ python3 src/main.py 
usage: main.py [-h] [--photoshop_password PHOTOSHOP_PASSWORD]
               --basnet_service_ip BASNET_SERVICE_IP
               [--basnet_service_host BASNET_SERVICE_HOST]
main.py: error: the following arguments are required: --basnet_service_ip


I am getting like this 

this is my code 
parser.add_argument('--photoshop_password', default='123456')
parser.add_argument('--basnet_service_ip', required=True, help="http://192.168.29.68:19002")
parser.add_argument('--basnet_service_host', help="Optional, the BASNet service host")

**Comment by cyrildiagne** [comment]
try :
```
parser.add_argument('--basnet_service_ip', default="http://192.168.29.68:19002")
```

**Comment by jardicc** [comment]
I had same issue, I did steps here. It didn't work but PC restart (windows) fixed it.

**Comment by homfarnam** [comment]
Hi 
I have this issue too and it didn't solve it.
`sudo pip3 install screenpoint                      1 ↵  2071  12:49:19
WARNING: The directory '/Users/farnam/Library/Caches/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting screenpoint
  Downloading screenpoint-0.1.2.tar.gz (2.8 kB)
ERROR: Could not find a version that satisfies the requirement opencv-contrib-python==3.4.2.17 (from screenpoint) (from versions: 3.4.11.45, 4.4.0.46)
ERROR: No matching distribution found for opencv-contrib-python==3.4.2.17 (from screenpoint)`

What should I do now?

I have macOS Catalina 10.15.7.
