### ISSUE TITLE
Server | Cut method response parsing | "Image do not match"

### ISSUE THREAD

**Issue by DIma-Kush** [cyrildiagne/ar-cutpaste#60]
It seems, on each image processing request, I'm receiving **ValueError: images do not match**.
For object detection service I'm using http://u2net-predictor.tenant-compass.global.coreweave.com, which works well as I see (200 status response).

```
INFO:werkzeug:192.168.0.102 - - [] "?[37mPOST /paste HTTP/1.1?[0m" 200 -
INFO:root: CUT
INFO:root: > sending to BASNet...
INFO:root:200
INFO:root: > saving results...
INFO:root: > opening mask...
INFO:root: > compositing final image...
INFO:werkzeug:192.168.0.102 - - [] "?[1m?[35mPOST /cut HTTP/1.1?[0m" 500 -
Traceback (most recent call last):
  File "C:\Users\Dmytro\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Dmytro\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\Dmytro\AppData\Local\Programs\Python\Python36\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\Dmytro\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Dmytro\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Dmytro\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Dmytro\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Dmytro\AppData\Local\Programs\Python\Python36\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\Dmytro\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Dmytro\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Dmytro\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Dmytro\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Dmytro\Personal\Develop\ar-cutpaste-master\server\src\main.py", line 92, in save
    img = Image.composite(ref, empty, mask)
  File "C:\Users\Dmytro\AppData\Local\Programs\Python\Python36\lib\site-packages\PIL\Image.py", line 2955, in composite
    image.paste(image1, None, mask)
  File "C:\Users\Dmytro\AppData\Local\Programs\Python\Python36\lib\site-packages\PIL\Image.py", line 1494, in paste
    self.im.paste(im, box, mask.im)
ValueError: images do not match
INFO:root: PASTE
INFO:root: > loading image...
INFO:root: > grabbing screenshot...
INFO:root: > finding projected point...
INFO:root:screen not found
INFO:root:Completed in 0.86s

```
cc @cyrildiagne

**Comment by spadoop** [comment]
Same error, using macOS with 2k resolution monitor.

**Comment by spadoop** [comment]
Fixed... `    mask = Image.open('cut_mask.png').convert("L").resize((256,256),resample=Image.BICUBIC, reducing_gap=2.0)
`
