### ISSUE TITLE
Paste 'perspectiveTransform' error

### ISSUE THREAD

**Issue by phanhongphucit** [cyrildiagne/ar-cutpaste#64]
I created the photoshop document with following setting:
- Width: 2121 pixels
- Height: 1280 pixels
- Resolution: 300 pixels/inch

The server/src/ps.py keep as default:
SCREEN_PIXELS_DENSITY = 2
DOC_OFFSET_X = 74 * SCREEN_PIXELS_DENSITY
DOC_OFFSET_Y = 130 * SCREEN_PIXELS_DENSITY
DOC_WIDTH = 2121
DOC_HEIGHT = 1280

When pasting I got this error:
INFO:werkzeug:192.168.43.1 - - [03/Jun/2020 11:44:40] "POST /paste HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/mac/Workspace/ar-cutpaste/server/venv/lib/python3.7/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/mac/Workspace/ar-cutpaste/server/venv/lib/python3.7/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/mac/Workspace/ar-cutpaste/server/venv/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/mac/Workspace/ar-cutpaste/server/venv/lib/python3.7/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/mac/Workspace/ar-cutpaste/server/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/mac/Workspace/ar-cutpaste/server/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/mac/Workspace/ar-cutpaste/server/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/mac/Workspace/ar-cutpaste/server/venv/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/mac/Workspace/ar-cutpaste/server/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/mac/Workspace/ar-cutpaste/server/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/mac/Workspace/ar-cutpaste/server/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/mac/Workspace/ar-cutpaste/server/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/mac/Workspace/ar-cutpaste/server/src/main.py", line 154, in paste
    x, y = screenpoint.project(view_arr, screen_arr, False)
  File "/Users/mac/Workspace/ar-cutpaste/server/venv/lib/python3.7/site-packages/screenpoint/screenpoint.py", line 39, in project
    dst = cv2.perspectiveTransform(pts, M)
cv2.error: OpenCV(3.4.2) /Users/travis/build/skvark/opencv-python/opencv/modules/core/src/matmul.cpp:2268: error: (-215:Assertion failed) scn + 1 == m.cols in function 'perspectiveTransform'
Am I setting correctly?
Where setting SCREEN_PIXELS_DENSITY and DOC_OFFSET?

Thanks!

**Comment by phanhongphucit** [comment]
I just added an image to the Background of photoshop document. It's resolved.
